name: Propagate Submodule via HTTPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      list: ${{ steps.set-matrix.outputs.list }}

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Fetch repo list
        id: set-matrix
        run: |
          REPOS=$(gh repo list your-org --limit 100 --json name -q '.[].name' \
            | grep '^website-' | jq -R . | jq -s .)
          echo "matrix={\"repo\": $REPOS}" >> $GITHUB_OUTPUT
          echo "list=$REPOS" >> $GITHUB_OUTPUT

  update-and-track:
    needs: get-repos
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        repo: [my-website-a, my-website-b]

    env:
      COMMON_REPO_URL: https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/your-org/astro-common-components.git
      COMMON_SUBMODULE_PATH: src/components/common
      BRANCH_NAME: update-common-submodule
      COMMIT_MESSAGE: "chore: update common submodule"
      PR_TITLE: "chore: update common submodule to latest main"
      PR_BODY: "This PR updates the common Astro submodule to the latest commit from `main`."

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Clone and update submodule manually
        run: |
          repo=${{ matrix.repo }}
          echo "📦 Cloning repo: $repo"
          git clone https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/your-org/$repo.git
          cd $repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "🔀 Switching to update branch"
          git checkout -B $BRANCH_NAME

          echo "🧹 Removing existing submodule directory"
          rm -rf $COMMON_SUBMODULE_PATH

          echo "⬇️ Cloning common components repo"
          git clone $COMMON_REPO_URL $COMMON_SUBMODULE_PATH
          cd $COMMON_SUBMODULE_PATH
          git checkout main
          cd ../../..

          echo "📌 Committing updated submodule pointer"
          git add $COMMON_SUBMODULE_PATH
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
          git push origin $BRANCH_NAME || echo "Nothing to push"

          echo "📨 Creating PR if not exists"
          PR_EXISTS=$(gh pr list --repo your-org/$repo --head $BRANCH_NAME --json number -q '.[0].number')
          if [[ -z "$PR_EXISTS" ]]; then
            gh pr create \
              --repo your-org/$repo \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --head "$BRANCH_NAME" \
              --base "main"
          fi
