name: Propagate Submodule via HTTPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      list: ${{ steps.set-matrix.outputs.list }}

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Fetch repo list
        id: set-matrix
        run: |
          REPOS=$(gh repo list SB-Hardik-Solanki --limit 100 --json name -q '.[].name' \
            | grep '^website-' | jq -R . | jq -s .)
          echo "matrix={\"repo\": $REPOS}" >> $GITHUB_OUTPUT
          echo "list=$REPOS" >> $GITHUB_OUTPUT

  update-and-track:
    needs: get-repos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [my-website-a, my-website-b]

    env:
      COMMON_REPO_URL: https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/my-common-components.git
      COMMON_SUBMODULE_PATH: src/shared
      BRANCH_NAME: update-common-submodule
      COMMIT_MESSAGE: "chore: update common submodule"
      PR_TITLE: "chore: update common submodule to latest main"
      PR_BODY: "This PR updates the common Astro submodule to the latest commit from `main`."

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Clone target repo
        run: |
          repo=${{ matrix.repo }}
          echo "📦 Cloning $repo"
          git clone https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/$repo.git
          cd $repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "🔀 Create or reset update branch"
          git checkout -B $BRANCH_NAME

          echo "🧹 Remove existing submodule directory"
          git rm -rf $COMMON_SUBMODULE_PATH || rm -rf $COMMON_SUBMODULE_PATH

          echo "➕ Add submodule cleanly via HTTPS"
          git submodule add -b main $COMMON_REPO_URL $COMMON_SUBMODULE_PATH
          git submodule update --init --recursive

          echo "🔎 Check if any changes need committing"
          git add .gitmodules $COMMON_SUBMODULE_PATH
          git diff --staged --quiet && echo "🟢 No changes detected, skipping commit/push/PR." && exit 0

          echo "✅ Committing submodule pointer update"
          git commit -m "$COMMIT_MESSAGE"

          echo "🚀 Pushing branch from HEAD to remote"
          git push https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/$repo.git HEAD:$BRANCH_NAME

          echo "🔍 Checking if remote branch exists"
          REF=$(git ls-remote --heads https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/$repo.git $BRANCH_NAME)

          if [ -n "$REF" ]; then
            echo "📨 Creating pull request"
            gh pr create \
              --repo SB-Hardik-Solanki/$repo \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --head "$BRANCH_NAME" \
              --base "main"
          else
            echo "⚠️ Branch $BRANCH_NAME not found on remote, skipping PR"
          fi
