name: Propagate Submodule via HTTPS + Dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      list: ${{ steps.set-matrix.outputs.list }}
      timestamp: ${{ steps.timestamp.outputs.branch_suffix }}

    steps:
      - name: 🧾 Checkout repository files
        uses: actions/checkout@v4

      - name: list files
        run: ls -l

      - name: 📥 Read repo list from repo-list.txt
        id: set-matrix
        run: |
          if [ ! -f repo-list.txt ]; then
            echo "❌ repo-list.txt not found!" >&2
            exit 1
          fi

          REPO_LIST=$(cat repo-list.txt | grep -v '^#' | grep -v '^\s*$' | jq -R . | jq -s .)
          echo "✅ Repo list parsed:"
          echo "$REPO_LIST"

          echo "matrix={\"repo\": $REPO_LIST}" >> $GITHUB_OUTPUT
          echo "list=$REPO_LIST" >> $GITHUB_OUTPUT

      - name: 🕒 Set dynamic branch suffix
        id: timestamp
        run: echo "branch_suffix=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

  update-and-track:
    needs: get-repos
    if: needs.get-repos.outputs.list != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-repos.outputs.matrix) }}

    env:
      COMMON_REPO_URL: https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/my-common-components.git
      COMMON_SUBMODULE_PATH: src/shared
      COMMIT_MESSAGE: "chore: update common submodule"
      PR_TITLE: "chore: update common submodule to latest main"
      PR_BODY: "This PR updates the common Astro submodule to the latest commit from `main`."

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Clone and update submodule
        run: |
          repo=${{ matrix.repo }}
          BRANCH_NAME="common-update-${{ needs.get-repos.outputs.timestamp }}"
          echo "📦 Cloning $repo"
          git clone https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/$repo.git
          cd $repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B $BRANCH_NAME

          echo "🧹 Remove old submodule"
          git rm -rf $COMMON_SUBMODULE_PATH || rm -rf $COMMON_SUBMODULE_PATH

          echo "➕ Add submodule via HTTPS"
          git submodule add -b main $COMMON_REPO_URL $COMMON_SUBMODULE_PATH
          git submodule update --init --recursive

          echo "🧼 Sanitize .gitmodules to remove token"
          sed -i 's|https://x-access-token:[^@]*@|https://|' .gitmodules

          echo "🔍 Check for changes"
          git add .gitmodules $COMMON_SUBMODULE_PATH
          git diff --staged --quiet && echo "🟢 No changes, skipping" && exit 0

          echo "✅ Commit submodule update"
          git commit -m "$COMMIT_MESSAGE"

          echo "🚀 Force-pushing to $BRANCH_NAME"
          git push --force https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/SB-Hardik-Solanki/$repo.git HEAD:$BRANCH_NAME

          echo "📨 Create pull request"
          gh pr create \
            --repo SB-Hardik-Solanki/$repo \
            --title "$PR_TITLE" \
            --body "$PR_BODY" \
            --head "$BRANCH_NAME" \
            --base "main"

  dashboard-and-publish:
    needs: get-repos
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Generate dashboard HTML
        run: |
          mkdir -p dashboard
          echo "<html><head><title>Submodule PR Dashboard</title></head><body><h1>📊 Submodule PR Status</h1>" > dashboard/index.html
          echo "<table border='1'><tr><th>Repo</th><th>PR</th><th>Status</th><th>Created</th></tr>" >> dashboard/index.html

          branch_name="common-update-${{ needs.get-repos.outputs.timestamp }}"
          repos=$(echo '${{ needs.get-repos.outputs.list }}' | jq -r '.[]')
          for repo in $repos; do
            PR=$(gh pr list --repo SB-Hardik-Solanki/$repo --head "$branch_name" --json number,state,url,createdAt -q '.[0]')
            if [[ "$PR" != "" ]]; then
              number=$(echo $PR | jq -r '.number')
              state=$(echo $PR | jq -r '.state')
              url=$(echo $PR | jq -r '.url')
              created=$(echo $PR | jq -r '.createdAt')
              echo "<tr><td>$repo</td><td><a href='$url'>#${number}</a></td><td>$state</td><td>$created</td></tr>" >> dashboard/index.html
            else
              echo "<tr><td>$repo</td><td>N/A</td><td>No PR</td><td>—</td></tr>" >> dashboard/index.html
            fi
          done

          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
          echo "</table><p>Last updated: $TIMESTAMP</p></body></html>" >> dashboard/index.html

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard
          publish_branch: gh-pages
