name: Propagate Submodule via HTTPS + Dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      list: ${{ steps.set-matrix.outputs.list }}
      timestamp: ${{ steps.timestamp.outputs.branch_suffix }}

    steps:
      - name: Install tools
        run: sudo apt-get install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_DEPLOY_TOKEN }}" | gh auth login --with-token

      - name: Fetch repo list
        id: set-matrix
        run: |
          REPOS=$(gh repo list SB-Hardik-Solanki --limit 100 --json name -q '.[].name' \
            | grep '^website-' | jq -R . | jq -s .)
          echo "matrix={\"repo\": $REPOS}" >> $GITHUB_OUTPUT
          echo "list=$REPOS" >> $GITHUB_OUTPUT

      - name: Set dynamic branch suffix
        id: timestamp
        run: echo "branch_suffix=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
